name: Playwright Tests
on:
  deployment_status:
jobs:
  set_env:
    runs-on: ubuntu-latest
    steps:
      - id: set
        run: |
          echo Event: ${{ github.event_name }}
          echo Deployment Status: ${{ toJson(github.event.deployment_status) }}
          echo Target URL: ${{ github.event.deployment_status.target_url }}
          echo State: ${{ github.event.deployment_status.state }}